### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dimon-mirchuk** [RomanPrygunkov/goit-markup-hw-02#3]
- именование классов абсолютно не по по ТЗ:
«B5» Имена классов описательные и понятные другому разработчику.
«B6» Имена классов не содержат заглавных букв, пробелов, транслита и названий тегов, только буквы и слова английского языка. Если имя класса состоит из нескольких слов, они разделяются дефисом.
- цвета, которые используются не один раз, лучше вынести в css переменные
- на body можно повесить больше дефолтных стилей, что бы дальше их не определять в нескольких местах. Есть такой паттерн DRY (don't repeat yourself), его очень желательно соблюдать.
Попробуй добавить на body:
  font-style
  font-weight
  font-size
  line-height
  letter-spacing
  Это сократит количество написанного тобой кода.

**Comment by RomanPrygunkov** [comment]
Исправил. Имена классов подправил, лучше пока ничего в голову не приходит ((  В body font-style не стал добавлять, т.к он почти везде стоит нормал по дефолту
